# This file was auto-generated by Fern from our API Definition.

import typing
from .string_variable_value import StringVariableValue
from .number_variable_value import NumberVariableValue
from .json_variable_value import JsonVariableValue
from .error_variable_value import ErrorVariableValue
from .function_call_variable_value import FunctionCallVariableValue
from .image_variable_value import ImageVariableValue

ArrayVariableValueItem = typing.Union[
    StringVariableValue,
    NumberVariableValue,
    JsonVariableValue,
    ErrorVariableValue,
    FunctionCallVariableValue,
    ImageVariableValue,
]
