# This file was auto-generated by Fern from our API Definition.

import typing
from .string_input_request import StringInputRequest
from .json_input_request import JsonInputRequest
from .chat_history_input_request import ChatHistoryInputRequest
from .number_input_request import NumberInputRequest
from .search_results_input_request import SearchResultsInputRequest
from .error_input_request import ErrorInputRequest
from .array_input_request import ArrayInputRequest
from .function_call_input_request import FunctionCallInputRequest

CodeExecutorInputRequest = typing.Union[
    StringInputRequest,
    JsonInputRequest,
    ChatHistoryInputRequest,
    NumberInputRequest,
    SearchResultsInputRequest,
    ErrorInputRequest,
    ArrayInputRequest,
    FunctionCallInputRequest,
]
