# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .indexing_config_vectorizer_request import IndexingConfigVectorizerRequest
import typing
from .document_index_chunking_request import DocumentIndexChunkingRequest
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class DocumentIndexIndexingConfigRequest(UniversalBaseModel):
    vectorizer: IndexingConfigVectorizerRequest
    chunking: typing.Optional[DocumentIndexChunkingRequest] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
