# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .error_execute_prompt_response import ErrorExecutePromptResponse
from .json_execute_prompt_response import JsonExecutePromptResponse
from .string_execute_prompt_response import StringExecutePromptResponse


class ExecutePromptResponse_Error(ErrorExecutePromptResponse):
    type: typing_extensions.Literal["ERROR"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class ExecutePromptResponse_Json(JsonExecutePromptResponse):
    type: typing_extensions.Literal["JSON"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class ExecutePromptResponse_String(StringExecutePromptResponse):
    type: typing_extensions.Literal["STRING"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


ExecutePromptResponse = typing.Union[
    ExecutePromptResponse_Error, ExecutePromptResponse_Json, ExecutePromptResponse_String
]
