# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .folder_entity_prompt_sandbox_data import FolderEntityPromptSandboxData
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class FolderEntityPromptSandbox(UniversalBaseModel):
    """
    A slim representation of a Prompt Sandbox, as it exists within a Folder.
    """

    id: str
    type: typing.Literal["PROMPT_SANDBOX"] = "PROMPT_SANDBOX"
    data: FolderEntityPromptSandboxData

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
