# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .google_vertex_ai_vectorizer_config import GoogleVertexAiVectorizerConfig
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class GoogleVertexAiVectorizerTextMultilingualEmbedding002(UniversalBaseModel):
    model_name: typing.Literal["text-multilingual-embedding-002"] = "text-multilingual-embedding-002"
    config: GoogleVertexAiVectorizerConfig

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
