# This file was auto-generated by Fern from our API Definition.

import typing

HostedByEnum = typing.Union[
    typing.Literal[
        "ANTHROPIC",
        "AWS_BEDROCK",
        "AZURE_OPENAI",
        "COHERE",
        "CUSTOM",
        "FIREWORKS_AI",
        "GOOGLE",
        "GOOGLE_VERTEX_AI",
        "GROQ",
        "HUGGINGFACE",
        "IBM_WATSONX",
        "MOSAICML",
        "MYSTIC",
        "OPENAI",
        "OPENPIPE",
        "PYQ",
        "REPLICATE",
    ],
    typing.Any,
]
