# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class InputVariableType(str, enum.Enum):
    """
    * `STRING` - STRING
    * `JSON` - JSON
    * `CHAT_HISTORY` - CHAT_HISTORY
    """

    STRING = "STRING"
    JSON = "JSON"
    CHAT_HISTORY = "CHAT_HISTORY"

    def visit(
        self,
        string: typing.Callable[[], T_Result],
        json: typing.Callable[[], T_Result],
        chat_history: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is InputVariableType.STRING:
            return string()
        if self is InputVariableType.JSON:
            return json()
        if self is InputVariableType.CHAT_HISTORY:
            return chat_history()
