# This file was auto-generated by Fern from our API Definition.

import typing
from .metadata_filter_config_request import MetadataFilterConfigRequest
from .metadata_filters_request import MetadataFiltersRequest

LegacySupportingMetadataFiltersRequest = typing.Union[MetadataFilterConfigRequest, MetadataFiltersRequest]
