# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .ml_model_display_tag import MlModelDisplayTag
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class MlModelDisplayConfigRequest(UniversalBaseModel):
    label: str
    description: str
    tags: typing.List[MlModelDisplayTag]
    default_display_priority: typing.Optional[float] = pydantic.Field(default=None)
    """
    For internal use only.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
