# This file was auto-generated by Fern from our API Definition.

import typing

MlModelFeature = typing.Union[
    typing.Literal[
        "TEXT",
        "CHAT_MESSAGE_SYSTEM",
        "CHAT_MESSAGE_USER",
        "CHAT_MESSAGE_ASSISTANT",
        "CHAT_MESSAGE_ASSISTANT_UNTERMINATED",
        "CHAT_MESSAGE_FUNCTION_CALL",
        "CHAT_MESSAGE_IMAGE",
        "FUNCTION_DEFINITION",
        "STREAMING_SUPPORT",
    ],
    typing.Any,
]
