# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic

from ..core.datetime_utils import serialize_datetime


class ModelVersionExecConfigParameters(pydantic.BaseModel):
    temperature: float
    max_tokens: int
    stop: typing.Optional[typing.List[str]]
    top_p: float
    top_k: typing.Optional[float]
    frequency_penalty: float
    presence_penalty: float
    logit_bias: typing.Optional[typing.Dict[str, typing.Optional[float]]]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        json_encoders = {dt.datetime: serialize_datetime}
