# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic

from ..core.datetime_utils import serialize_datetime


class ModelVersionCompiledPrompt(pydantic.BaseModel):
    text: str = pydantic.Field(
        description=(
            "The fully compiled prompt in normalized ChatML syntax after all variable substitutions and templating functions are applied.\n"
        )
    )
    num_tokens: int = pydantic.Field(description=("The approximate number of tokens used by the compiled prompt.\n"))

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        json_encoders = {dt.datetime: serialize_datetime}
