# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from .boolean_parameter_config_request import BooleanParameterConfigRequest
from .const_parameter_config_request import ConstParameterConfigRequest
from .integer_parameter_config_request import IntegerParameterConfigRequest
from .number_parameter_config_request import NumberParameterConfigRequest
from .string_parameter_config_request import StringParameterConfigRequest


class ParameterConfigRequest_Array(ArrayParameterConfigRequest):
    type: typing.Literal["array"] = "array"

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class ParameterConfigRequest_Object(ObjectParameterConfigRequest):
    type: typing.Literal["object"] = "object"

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class ParameterConfigRequest_Integer(IntegerParameterConfigRequest):
    type: typing.Literal["integer"] = "integer"

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class ParameterConfigRequest_Number(NumberParameterConfigRequest):
    type: typing.Literal["number"] = "number"

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class ParameterConfigRequest_String(StringParameterConfigRequest):
    type: typing.Literal["string"] = "string"

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class ParameterConfigRequest_Boolean(BooleanParameterConfigRequest):
    type: typing.Literal["boolean"] = "boolean"

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class ParameterConfigRequest_OneOf(OneOfParameterConfigRequest):
    type: typing.Literal["oneOf"] = "oneOf"

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class ParameterConfigRequest_Const(ConstParameterConfigRequest):
    type: typing.Literal["const"] = "const"

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


ParameterConfigRequest = typing.Union[
    ParameterConfigRequest_Array,
    ParameterConfigRequest_Object,
    ParameterConfigRequest_Integer,
    ParameterConfigRequest_Number,
    ParameterConfigRequest_String,
    ParameterConfigRequest_Boolean,
    ParameterConfigRequest_OneOf,
    ParameterConfigRequest_Const,
]
from .array_parameter_config_request import ArrayParameterConfigRequest  # noqa: E402
from .object_parameter_config_request import ObjectParameterConfigRequest  # noqa: E402
from .one_of_parameter_config_request import OneOfParameterConfigRequest  # noqa: E402

ParameterConfigRequest_Array.update_forward_refs(
    ArrayParameterConfigRequest=ArrayParameterConfigRequest,
    ObjectParameterConfigRequest=ObjectParameterConfigRequest,
    OneOfParameterConfigRequest=OneOfParameterConfigRequest,
    ParameterConfigRequest=ParameterConfigRequest,
)
ParameterConfigRequest_Object.update_forward_refs(
    ArrayParameterConfigRequest=ArrayParameterConfigRequest,
    ObjectParameterConfigRequest=ObjectParameterConfigRequest,
    OneOfParameterConfigRequest=OneOfParameterConfigRequest,
    ParameterConfigRequest=ParameterConfigRequest,
)
ParameterConfigRequest_OneOf.update_forward_refs(
    ArrayParameterConfigRequest=ArrayParameterConfigRequest,
    ObjectParameterConfigRequest=ObjectParameterConfigRequest,
    OneOfParameterConfigRequest=OneOfParameterConfigRequest,
    ParameterConfigRequest=ParameterConfigRequest,
)
