# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .error_variable_value import ErrorVariableValue
from .json_variable_value import JsonVariableValue
from .string_variable_value import StringVariableValue


class PromptOutput_String(StringVariableValue):
    type: typing_extensions.Literal["STRING"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class PromptOutput_Json(JsonVariableValue):
    type: typing_extensions.Literal["JSON"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class PromptOutput_Error(ErrorVariableValue):
    type: typing_extensions.Literal["ERROR"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


PromptOutput = typing.Union[PromptOutput_String, PromptOutput_Json, PromptOutput_Error]
