# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class PromptTemplateBlockState(str, enum.Enum):
    """
    - `ENABLED` - ENABLED
    - `DISABLED` - DISABLED
    """

    ENABLED = "ENABLED"
    DISABLED = "DISABLED"

    def visit(self, enabled: typing.Callable[[], T_Result], disabled: typing.Callable[[], T_Result]) -> T_Result:
        if self is PromptTemplateBlockState.ENABLED:
            return enabled()
        if self is PromptTemplateBlockState.DISABLED:
            return disabled()
