# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .test_suite_run_deployment_release_tag_exec_config import TestSuiteRunDeploymentReleaseTagExecConfig
from .test_suite_run_workflow_release_tag_exec_config import TestSuiteRunWorkflowReleaseTagExecConfig


class TestSuiteRunExecConfig_DeploymentReleaseTag(TestSuiteRunDeploymentReleaseTagExecConfig):
    type: typing_extensions.Literal["DEPLOYMENT_RELEASE_TAG"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class TestSuiteRunExecConfig_WorkflowReleaseTag(TestSuiteRunWorkflowReleaseTagExecConfig):
    type: typing_extensions.Literal["WORKFLOW_RELEASE_TAG"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


TestSuiteRunExecConfig = typing.Union[
    TestSuiteRunExecConfig_DeploymentReleaseTag, TestSuiteRunExecConfig_WorkflowReleaseTag
]
