# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .test_case_chat_history_variable_value import TestCaseChatHistoryVariableValue
from .test_case_error_variable_value import TestCaseErrorVariableValue
from .test_case_json_variable_value import TestCaseJsonVariableValue
from .test_case_number_variable_value import TestCaseNumberVariableValue
from .test_case_search_results_variable_value import TestCaseSearchResultsVariableValue
from .test_case_string_variable_value import TestCaseStringVariableValue


class TestCaseVariableValue_String(TestCaseStringVariableValue):
    type: typing_extensions.Literal["STRING"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class TestCaseVariableValue_Number(TestCaseNumberVariableValue):
    type: typing_extensions.Literal["NUMBER"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class TestCaseVariableValue_Json(TestCaseJsonVariableValue):
    type: typing_extensions.Literal["JSON"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class TestCaseVariableValue_ChatHistory(TestCaseChatHistoryVariableValue):
    type: typing_extensions.Literal["CHAT_HISTORY"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class TestCaseVariableValue_SearchResults(TestCaseSearchResultsVariableValue):
    type: typing_extensions.Literal["SEARCH_RESULTS"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class TestCaseVariableValue_Error(TestCaseErrorVariableValue):
    type: typing_extensions.Literal["ERROR"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


TestCaseVariableValue = typing.Union[
    TestCaseVariableValue_String,
    TestCaseVariableValue_Number,
    TestCaseVariableValue_Json,
    TestCaseVariableValue_ChatHistory,
    TestCaseVariableValue_SearchResults,
    TestCaseVariableValue_Error,
]
