# This file was auto-generated by Fern from our API Definition.

import typing

WorkflowExecutionEventErrorCode = typing.Union[
    typing.Literal[
        "WORKFLOW_INITIALIZATION",
        "WORKFLOW_CANCELLED",
        "NODE_EXECUTION_COUNT_LIMIT_REACHED",
        "INTERNAL_SERVER_ERROR",
        "NODE_EXECUTION",
        "LLM_PROVIDER",
        "INVALID_TEMPLATE",
        "USER_DEFINED_ERROR",
    ],
    typing.Any,
]
