# This file was auto-generated by Fern from our API Definition.

from vellum import Vellum
from vellum import AsyncVellum


async def test_add_entity_to_folder(client: Vellum, async_client: AsyncVellum) -> None:
    # Type ignore to avoid mypy complaining about the function not being meant to return a value
    assert (
        client.folder_entities.add_entity_to_folder(folder_id="folder_id", entity_id="entity_id")  # type: ignore[func-returns-value]
        is None
    )

    assert (
        await async_client.folder_entities.add_entity_to_folder(folder_id="folder_id", entity_id="entity_id")  # type: ignore[func-returns-value]
        is None
    )
