# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .deployment_provider_payload_response_payload import DeploymentProviderPayloadResponsePayload
import typing
from .compile_prompt_meta import CompilePromptMeta
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class DeploymentProviderPayloadResponse(UniversalBaseModel):
    payload: DeploymentProviderPayloadResponsePayload
    meta: typing.Optional[CompilePromptMeta] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
