# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .vellum_error_request import VellumErrorRequest
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class ErrorVellumValueRequest(UniversalBaseModel):
    """
    A value representing an Error.
    """

    type: typing.Literal["ERROR"] = "ERROR"
    value: typing.Optional[VellumErrorRequest] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
