# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .folder_entity_document_index_data import FolderEntityDocumentIndexData
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class FolderEntityDocumentIndex(UniversalBaseModel):
    """
    A slim representation of a Document Index, as it exists within a Folder.
    """

    id: str
    type: typing.Literal["DOCUMENT_INDEX"] = "DOCUMENT_INDEX"
    data: FolderEntityDocumentIndexData

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
