# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class RawPromptExecutionOverridesRequest(UniversalBaseModel):
    body: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = None
    headers: typing.Optional[typing.Dict[str, typing.Optional[str]]] = pydantic.Field(default=None)
    """
    The raw headers to send to the model host.
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    The raw URL to send to the model host.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
