# This file was auto-generated by Fern from our API Definition.

import typing
from .variable_prompt_block import VariablePromptBlock
from .plain_text_prompt_block import PlainTextPromptBlock

RichTextChildBlock = typing.Union[VariablePromptBlock, PlainTextPromptBlock]
