# This file was auto-generated by Fern from our API Definition.

from vellum import Vellum
from vellum import AsyncVellum
import typing
from .utilities import validate_response
from vellum import StringInputRequest


async def test_list_(client: Vellum, async_client: AsyncVellum) -> None:
    expected_response: typing.Any = {
        "count": 123,
        "next": "http://api.example.org/accounts/?offset=400&limit=100",
        "previous": "http://api.example.org/accounts/?offset=200&limit=100",
        "results": [
            {
                "id": "id",
                "created": "2024-01-15T09:30:00Z",
                "label": "label",
                "name": "name",
                "status": "ACTIVE",
                "environment": "DEVELOPMENT",
                "last_deployed_on": "2024-01-15T09:30:00Z",
                "input_variables": [{"id": "id", "key": "key", "type": "STRING"}],
                "description": "description",
            }
        ],
    }
    expected_types: typing.Any = {
        "count": "integer",
        "next": None,
        "previous": None,
        "results": (
            "list",
            {
                0: {
                    "id": None,
                    "created": "datetime",
                    "label": None,
                    "name": None,
                    "status": None,
                    "environment": None,
                    "last_deployed_on": "datetime",
                    "input_variables": ("list", {0: {"id": None, "key": None, "type": None}}),
                    "description": None,
                }
            },
        ),
    }
    response = client.deployments.list()
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.deployments.list()
    validate_response(async_response, expected_response, expected_types)


async def test_retrieve(client: Vellum, async_client: AsyncVellum) -> None:
    expected_response: typing.Any = {
        "id": "id",
        "created": "2024-01-15T09:30:00Z",
        "label": "label",
        "name": "name",
        "status": "ACTIVE",
        "environment": "DEVELOPMENT",
        "last_deployed_on": "2024-01-15T09:30:00Z",
        "input_variables": [
            {"id": "id", "key": "key", "type": "STRING", "required": True, "default": {"type": "STRING"}}
        ],
        "description": "description",
        "active_model_version_ids": ["active_model_version_ids"],
        "last_deployed_history_item_id": "last_deployed_history_item_id",
    }
    expected_types: typing.Any = {
        "id": None,
        "created": "datetime",
        "label": None,
        "name": None,
        "status": None,
        "environment": None,
        "last_deployed_on": "datetime",
        "input_variables": (
            "list",
            {0: {"id": None, "key": None, "type": None, "required": None, "default": {"type": None}}},
        ),
        "description": None,
        "active_model_version_ids": ("list", {0: None}),
        "last_deployed_history_item_id": None,
    }
    response = client.deployments.retrieve(id="id")
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.deployments.retrieve(id="id")
    validate_response(async_response, expected_response, expected_types)


async def test_list_deployment_release_tags(client: Vellum, async_client: AsyncVellum) -> None:
    expected_response: typing.Any = {
        "count": 123,
        "next": "http://api.example.org/accounts/?offset=400&limit=100",
        "previous": "http://api.example.org/accounts/?offset=200&limit=100",
        "results": [
            {"name": "name", "source": "SYSTEM", "history_item": {"id": "id", "timestamp": "2024-01-15T09:30:00Z"}}
        ],
    }
    expected_types: typing.Any = {
        "count": "integer",
        "next": None,
        "previous": None,
        "results": ("list", {0: {"name": None, "source": None, "history_item": {"id": None, "timestamp": "datetime"}}}),
    }
    response = client.deployments.list_deployment_release_tags(id="id")
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.deployments.list_deployment_release_tags(id="id")
    validate_response(async_response, expected_response, expected_types)


async def test_retrieve_deployment_release_tag(client: Vellum, async_client: AsyncVellum) -> None:
    expected_response: typing.Any = {
        "name": "name",
        "source": "SYSTEM",
        "history_item": {"id": "id", "timestamp": "2024-01-15T09:30:00Z"},
    }
    expected_types: typing.Any = {"name": None, "source": None, "history_item": {"id": None, "timestamp": "datetime"}}
    response = client.deployments.retrieve_deployment_release_tag(id="id", name="name")
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.deployments.retrieve_deployment_release_tag(id="id", name="name")
    validate_response(async_response, expected_response, expected_types)


async def test_update_deployment_release_tag(client: Vellum, async_client: AsyncVellum) -> None:
    expected_response: typing.Any = {
        "name": "name",
        "source": "SYSTEM",
        "history_item": {"id": "id", "timestamp": "2024-01-15T09:30:00Z"},
    }
    expected_types: typing.Any = {"name": None, "source": None, "history_item": {"id": None, "timestamp": "datetime"}}
    response = client.deployments.update_deployment_release_tag(id="id", name="name")
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.deployments.update_deployment_release_tag(id="id", name="name")
    validate_response(async_response, expected_response, expected_types)


async def test_retrieve_provider_payload(client: Vellum, async_client: AsyncVellum) -> None:
    expected_response: typing.Any = {
        "payload": {"key": "value"},
        "meta": {
            "model_name": "model_name",
            "deployment_release_tag": "deployment_release_tag",
            "prompt_version_id": "prompt_version_id",
        },
    }
    expected_types: typing.Any = {
        "payload": ("dict", {0: (None, None)}),
        "meta": {"model_name": None, "deployment_release_tag": None, "prompt_version_id": None},
    }
    response = client.deployments.retrieve_provider_payload(inputs=[StringInputRequest(name="name", value="value")])
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.deployments.retrieve_provider_payload(
        inputs=[StringInputRequest(name="name", value="value")]
    )
    validate_response(async_response, expected_response, expected_types)
