# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations


class VellumEnvironment:
    PROD: VellumEnvironment

    predict: str
    document: str

    def __init__(self, *, predict: str, document: str):
        self.predict = predict
        self.document = document


VellumEnvironment.PROD = VellumEnvironment(predict="https://predict.vellum.ai",
                                           document="https://documents.vellum.ai")
